### PR TITLE
Fix subcommands not being deleted when option is true

### LINKED ISSUE #176: Subcommands cannot delete messages.
Hi there,

I noticed that subcommands cannot control the deletion of their command message like top level commands can.

A simple test: Register any commands in this configuration:
bot -> command (deleteCommand: false) -> subcommand (deleteCommand: true)

if you then call **command subcommand** the command message wont be deleted.

Only top level commands can control deletion of the command message it would seem. 
Since Command.regiterSubcommand has the deleteCommand variable, is this intentional?

Thanks

### PR DESCRIPTION
**Pull request by MergHQ**
Closes #176

Don't know if this is really a good solution 🤔 , but it works! 🍻

### CODE REVIEW

File: lib/command/Command.js [hunk 1]
```diff
@@ -156,13 +156,20 @@ class Command {
...
         if(!this.permissionCheck(msg)) {
             if(this.permissionMessage) {
                 msg.channel.createMessage(this.permissionMessage);
             }
             return;
         }
+        if (this.deleteCommand && msg.channel.guild && msg.channel.permissionsOf(client.user.id).has('manageMessages')) {
+            let originalExec = this.execute;
+            this.execute = (msg, args) => {
+                client.deleteMessage(msg.channel.id, msg.id);
```
Comment (abalabahaha) [inline lib/command/Command.js]: This can be done directly through the Message object, removing the need to pass client

File: lib/command/Command.js [hunk 2]
```diff
@@ -156,13 +156,20 @@ class Command {
...
 
-    process(args, msg) {
+    process(args, msg, client) {
         if(!this.permissionCheck(msg)) {
             if(this.permissionMessage) {
                 msg.channel.createMessage(this.permissionMessage);
             }
             return;
         }
+        if (this.deleteCommand && msg.channel.guild && msg.channel.permissionsOf(client.user.id).has('manageMessages')) {
```
Comment (abalabahaha) [inline lib/command/Command.js]: Use a bitwise permissions check here

File: lib/command/Command.js [hunk 3]
```diff
@@ -156,13 +156,20 @@ class Command {
...
+            let originalExec = this.execute;
+            this.execute = (msg, args) => {
```
Comment (abalabahaha) [inline lib/command/Command.js]: You shouldn't need to replace the execute method to delete the message

**Review by abalabahaha — CHANGES_REQUESTED** [review]

File: lib/command/Command.js (hunk 3 above)
Comment (MergHQ) [reply lib/command/Command.js]: If the main command has `deleteCommand: true` but the subcommand has `deleteCommand: false` the message will still be deleted even if the user calls the subcommand since the main command is processed before the subcommand.

I guess I could add the delete check before execute is called.

File: lib/command/Command.js [hunk 4]
```diff
@@ -163,10 +163,12 @@ class Command {
             }
             return;
         }
-        if (this.deleteCommand && msg.channel.guild && msg.channel.permissionsOf(client.user.id).has('manageMessages')) {
+        if (this.deleteCommand && msg.channel.guild) {
             let originalExec = this.execute;
             this.execute = (msg, args) => {
-                msg.delete();
+                msg.delete().catch(e => {
```
Comment (abalabahaha) [inline lib/command/Command.js]: Should've left the preemptive check in

**Comment by abalabahaha** [comment]
Whoops, outdated diff, ignore that.

EDIT: actually, can you add the perms check back?

**Review by abalabahaha — APPROVED** [review]
