### PR TITLE
Text in Guild Voice Channels

### LINKED ISSUE #1381: Text in voice channels crashing
Discord recently rolled out text in voice channels (see https://support.discord.com/hc/en-us/articles/4412085582359)
When a message is sent in one of these it crashes Eris.
```
node:events:368
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'add')
    at Shard.wsEvent (/home/shorty/projects/DoTheMario/node_modules/eris/lib/gateway/Shard.js:853:65)
    at Shard.onPacket (/home/shorty/projects/DoTheMario/node_modules/eris/lib/gateway/Shard.js:402:26)
    at Shard._onWSMessage (/home/shorty/projects/DoTheMario/node_modules/eris/lib/gateway/Shard.js:2446:29)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage (/home/shorty/projects/DoTheMario/node_modules/ws/lib/websocket.js:1169:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage (/home/shorty/projects/DoTheMario/node_modules/ws/lib/receiver.js:528:14)
    at Receiver.getData (/home/shorty/projects/DoTheMario/node_modules/ws/lib/receiver.js:446:17)
    at Receiver.startLoop (/home/shorty/projects/DoTheMario/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/shorty/projects/DoTheMario/node_modules/ws/lib/receiver.js:83:10)
Emitted 'error' event on Client instance at:
    at Shard.emit (/home/shorty/projects/DoTheMario/node_modules/eris/lib/gateway/Shard.js:242:26)
    at Shard._onWSMessage (/home/shorty/projects/DoTheMario/node_modules/eris/lib/gateway/Shard.js:2449:18)
    at WebSocket.emit (node:events:390:28)
    [... lines matching original stack trace ...]
    at Receiver._write (/home/shorty/projects/DoTheMario/node_modules/ws/lib/receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
```

### PR DESCRIPTION
**Pull request by beanjo55**
Adds support for upcoming text in guild voice channels, draft until discord finalizes the spec for them and is no longer subject to change. Only applies to GUILD_VOICE, stage channels not included

TODO:
- [X] Create GuildVoiceChannel class, extends VoiceChannel, and add appropriate text props since no multiple inheritance :(
- [X] Update channel struct to use new GuildVoiceChannel class
- [X] First pass as TS typings
- [x] Check jsdoc to use the new channel class and the channel is referenced where appropriate
- [x] Fix TS type issue with messages collection
- [x] Ensure lint is correct

Please let me know if i missed anything, or if theres a better or more appropriate way to implement!

Fixes #1381

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -3421,13 +3456,13 @@ declare namespace Eris {
...
 
-  export class TextChannel extends GuildChannel implements GuildTextable, Invitable {
+  export class TextChannel extends GuildChannel implements GuildTextable, Invitable, GuildPinnable {
     defaultAutoArchiveDuration: AutoArchiveDuration;
     lastMessageID: string;
     lastPinTimestamp: number | null;
     messages: Collection<Message<this>>;
     rateLimitPerUser: number;
-    topic: string | null;
+    topic?: string;
```
Comment (DonovanDMC) [inline index.d.ts]:
```suggestion
    topic?: string | null;
```
topic is both optional and nullable
image

File: index.d.ts [hunk 2]
```diff
@@ -293,10 +293,20 @@ declare namespace Eris {
...
+
+  interface Pinnable {
+	getPins(): Promise<Message[]>;
+    pinMessage(messageID: string): Promise<void>;
+	unpinMessage(messageID: string): Promise<void>;
+  }
+
+  interface GuildPinnable extends Pinnable {
+	lastPinTimestamp: number | null;
+	topic?: string;
```
Comment (DonovanDMC) [inline index.d.ts]:
```suggestion
	topic?: string | nullable;
```

**Review by DonovanDMC — APPROVED** [review]

**Review by bsian03 — APPROVED** [review]
If there are any more issues, we can fix them in subsequent PRs
