### PR TITLE
Fix clean content for custom emotes and system messages

### LINKED ISSUE #377: Message.cleanContent fails on Discord-generated messages and custom emojis
By Discord-generated messages I mean the ones for pinning a message in a channel and for a member joining the server. In these cases the mention `<@id>` remains in `cleanContent` when it should be replaced by username.

Custom emojis are a similar story, they should be replaced by the emoji name i.e. `<:custom:id>` -> `:custom:`

### PR DESCRIPTION
**Pull request by TheRacingLion**
Fixes #377. Open to suggestions and/or improvements. Feel free to edit or comment on anything.

### CODE REVIEW

File: lib/structures/Message.js [hunk 1]
```diff
@@ -128,15 +128,28 @@ class Message extends Base {
...
+                if(mention) {
+                    if(this.channel.guild) {
+                        var member = this.channel.guild.members.get(mentionId);
+                        if(member && member.nick) {
+                            return "@" + member.nick;
+                        }
                     }
+                    return "@" + mention.username;
+                } else if(this.author && (this.type === 6 || this.type === 7)) {
+                    return "@" + this.author.username;
```
Comment (TheRacingLion) [inline lib/structures/Message.js]: This only replaces with the mention's username. To work fully, it should instead test for a nick like the checks above. Most likely needs refactoring.
