### PR TITLE
make error properties writable

### LINKED ISSUE #535: Warning: a promise was rejected with a non-error
Since some recent Node.js version, Node will now emit warnings if you reject a Promise with a non-`Error` type. Some things in Eris aren't rejected with errors, such as `Client#getInvite()`. I don't know of any other ones, but I'd assume there is more. Any ETA on a fix? This is currently filling up my logs, and I'd really like to stay away from `--no-warnings`.

After digging some more, I found something odd...
`(node:3317) Warning: a promise was rejected with a non-error: [object Error]`

### PR DESCRIPTION
**Pull request by alex-taxiera**
Fixes #535

### CODE REVIEW

File: lib/errors/DiscordHTTPError.js [hunk 1]
```diff
@@ -17,13 +17,19 @@ class DiscordHTTPError extends Error {
             value: response
         });
 
-        this.code = res.statusCode;
+        Object.defineProperty(this, "code", {
+            enumerable: false,
```
Comment (apacheli) [inline lib/errors/DiscordHTTPError.js:21]: Object.defineProperty() sets `enumerable` to `false` by default, so it can be removed, but it probably wouldn't matter much

**Review by apacheli — CHANGES_REQUESTED** [review]

File: lib/errors/DiscordHTTPError.js (hunk 1 above)
Comment (alex-taxiera) [reply lib/errors/DiscordHTTPError.js:21]: considering that people suggested I don't use `Object.defineProperty` if "all I was doing" was `value: thing` it may be best to be more declarative.
