### PR TITLE
fix(Member): fix voice state not updated when `member` field is missing.

### LINKED ISSUE #1522: Voice state not added when the bot starts
If I'm connected to a channel and it starts, the bot doesn't add a voiceState.
before the update, it worked fine
https://github.com/abalabahaha/eris/pull/1521

### PR DESCRIPTION
**Pull request by babiabeo**
Fix: #1522

Currently, the voice state is only updated if the data has `member` field. However, the `member` field is optional in [Voice State object](https://discord.com/developers/docs/resources/voice#voice-state-object-voice-state-structure), leading to incorrect update handling. This PR ensures that the voice state is updated even when the `member` field is not present.

### CODE REVIEW

**Comment by bsian03** [comment]
Thanks for getting this - will review and test soon
cc @flav-code

**Review by TTtie — APPROVED** [review]
From my very brief local testing, it seems to be working, both at startup and while the voice state is updated with the new member data!

File: lib/structures/Member.js [hunk 1]
```diff
@@ -88,7 +88,9 @@ class Member extends Base {
             } else if(data.channel_id || data.mute || data.deaf || data.suppress) {
                 this.guild.voiceStates.update(data);
             }
-            data = data.member;
+            if(data.hasOwnProperty("member")){
```
Comment (TTtie) [inline lib/structures/Member.js]: a very small style nit I just noticed, there should be a space between the if condition and the block inside
```suggestion
            if(data.hasOwnProperty("member")) {
```

**Comment by flav-code** [comment]
LGTM

**Review by flav-code — CHANGES_REQUESTED** [review]
Style

**Comment by flav-code** [comment]
image

**Comment by babiabeo** [comment]
It is weird that the linter doesn't detect that one.

**Comment by bsian03** [comment]
Will fix the linter, otherwise lgtm
